namespace Xrm.RecordsRestorator.Plugin
{
    partial class MyPluginControl
    {
        /// <summary> 
        /// Variable nécessaire au concepteur.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Nettoyage des ressources utilisées.
        /// </summary>
        /// <param name="disposing">true si les ressources managées doivent être supprimées ; sinon, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by component designer
        private void InitializeComponent()
        {
            this.toolStripMenu = new System.Windows.Forms.ToolStrip();
            this.tsbClose = new System.Windows.Forms.ToolStripButton();
            this.entitiesCb = new System.Windows.Forms.ComboBox();
            this.entityLabel = new System.Windows.Forms.Label();
            this.usernameLabel = new System.Windows.Forms.Label();
            this.usersCb = new System.Windows.Forms.ComboBox();
            this.fetchRecordsBtn = new System.Windows.Forms.Button();
            this.deletedRecordGrid = new System.Windows.Forms.DataGridView();
            this.Id = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.ObjectId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Entity = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.UserId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.CreatedDate = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.detailsDataGrid = new System.Windows.Forms.DataGridView();
            this.Attribute = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Value = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.restoreRecordsButton = new System.Windows.Forms.Button();
            this.toolStripMenu.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.deletedRecordGrid)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.detailsDataGrid)).BeginInit();
            this.SuspendLayout();
            // 
            // toolStripMenu
            // 
            this.toolStripMenu.ImageScalingSize = new System.Drawing.Size(24, 24);
            this.toolStripMenu.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.tsbClose});
            this.toolStripMenu.Location = new System.Drawing.Point(0, 0);
            this.toolStripMenu.Name = "toolStripMenu";
            this.toolStripMenu.Size = new System.Drawing.Size(1162, 25);
            this.toolStripMenu.TabIndex = 4;
            this.toolStripMenu.Text = "toolStrip1";
            // 
            // tsbClose
            // 
            this.tsbClose.Alignment = System.Windows.Forms.ToolStripItemAlignment.Right;
            this.tsbClose.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.tsbClose.Name = "tsbClose";
            this.tsbClose.Size = new System.Drawing.Size(86, 22);
            this.tsbClose.Text = "Close this tool";
            this.tsbClose.Click += new System.EventHandler(this.tsbClose_Click);
            // 
            // entitiesCb
            // 
            this.entitiesCb.FormattingEnabled = true;
            this.entitiesCb.Location = new System.Drawing.Point(72, 26);
            this.entitiesCb.Name = "entitiesCb";
            this.entitiesCb.Size = new System.Drawing.Size(148, 21);
            this.entitiesCb.TabIndex = 6;
            this.entitiesCb.SelectedIndexChanged += new System.EventHandler(this.entitiesCb_SelectedIndexChanged);
            // 
            // entityLabel
            // 
            this.entityLabel.AutoSize = true;
            this.entityLabel.Location = new System.Drawing.Point(13, 29);
            this.entityLabel.Name = "entityLabel";
            this.entityLabel.Size = new System.Drawing.Size(33, 13);
            this.entityLabel.TabIndex = 7;
            this.entityLabel.Text = "Entity";
            // 
            // usernameLabel
            // 
            this.usernameLabel.AutoSize = true;
            this.usernameLabel.Location = new System.Drawing.Point(11, 56);
            this.usernameLabel.Name = "usernameLabel";
            this.usernameLabel.Size = new System.Drawing.Size(55, 13);
            this.usernameLabel.TabIndex = 8;
            this.usernameLabel.Text = "Username";
            // 
            // usersCb
            // 
            this.usersCb.FormattingEnabled = true;
            this.usersCb.Location = new System.Drawing.Point(72, 53);
            this.usersCb.Name = "usersCb";
            this.usersCb.Size = new System.Drawing.Size(148, 21);
            this.usersCb.TabIndex = 9;
            this.usersCb.SelectedIndexChanged += new System.EventHandler(this.usersCb_SelectedIndexChanged);
            // 
            // fetchRecordsBtn
            // 
            this.fetchRecordsBtn.Location = new System.Drawing.Point(16, 80);
            this.fetchRecordsBtn.Name = "fetchRecordsBtn";
            this.fetchRecordsBtn.Size = new System.Drawing.Size(204, 23);
            this.fetchRecordsBtn.TabIndex = 10;
            this.fetchRecordsBtn.Text = "Fetch Records";
            this.fetchRecordsBtn.UseVisualStyleBackColor = true;
            this.fetchRecordsBtn.Click += new System.EventHandler(this.fetchRecordsBtn_Click);
            // 
            // deletedRecordGrid
            // 
            this.deletedRecordGrid.AllowUserToAddRows = false;
            this.deletedRecordGrid.AllowUserToDeleteRows = false;
            this.deletedRecordGrid.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.deletedRecordGrid.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.deletedRecordGrid.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Id,
            this.ObjectId,
            this.Entity,
            this.UserId,
            this.CreatedDate});
            this.deletedRecordGrid.Location = new System.Drawing.Point(14, 132);
            this.deletedRecordGrid.Name = "deletedRecordGrid";
            this.deletedRecordGrid.ReadOnly = true;
            this.deletedRecordGrid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.deletedRecordGrid.ShowCellErrors = false;
            this.deletedRecordGrid.ShowEditingIcon = false;
            this.deletedRecordGrid.ShowRowErrors = false;
            this.deletedRecordGrid.Size = new System.Drawing.Size(620, 338);
            this.deletedRecordGrid.TabIndex = 12;
            this.deletedRecordGrid.Click += new System.EventHandler(this.deletedRecordGrid_Click);
            // 
            // Id
            // 
            this.Id.DataPropertyName = "Id";
            this.Id.HeaderText = "ID";
            this.Id.Name = "Id";
            this.Id.ReadOnly = true;
            this.Id.Visible = false;
            // 
            // ObjectId
            // 
            this.ObjectId.DataPropertyName = "ObjectId";
            this.ObjectId.HeaderText = "Object";
            this.ObjectId.Name = "ObjectId";
            this.ObjectId.ReadOnly = true;
            this.ObjectId.Width = 220;
            // 
            // Entity
            // 
            this.Entity.DataPropertyName = "Entity";
            this.Entity.HeaderText = "Entity";
            this.Entity.Name = "Entity";
            this.Entity.ReadOnly = true;
            // 
            // UserId
            // 
            this.UserId.DataPropertyName = "UserId";
            this.UserId.HeaderText = "User";
            this.UserId.Name = "UserId";
            this.UserId.ReadOnly = true;
            this.UserId.Width = 150;
            // 
            // CreatedDate
            // 
            this.CreatedDate.DataPropertyName = "CreatedDate";
            this.CreatedDate.HeaderText = "Date";
            this.CreatedDate.Name = "CreatedDate";
            this.CreatedDate.ReadOnly = true;
            // 
            // detailsDataGrid
            // 
            this.detailsDataGrid.AllowUserToAddRows = false;
            this.detailsDataGrid.AllowUserToDeleteRows = false;
            this.detailsDataGrid.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.detailsDataGrid.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.detailsDataGrid.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Attribute,
            this.Value});
            this.detailsDataGrid.Location = new System.Drawing.Point(660, 132);
            this.detailsDataGrid.MultiSelect = false;
            this.detailsDataGrid.Name = "detailsDataGrid";
            this.detailsDataGrid.ReadOnly = true;
            this.detailsDataGrid.ShowEditingIcon = false;
            this.detailsDataGrid.Size = new System.Drawing.Size(470, 338);
            this.detailsDataGrid.TabIndex = 13;
            // 
            // Attribute
            // 
            this.Attribute.DataPropertyName = "Key";
            this.Attribute.HeaderText = "Attribute";
            this.Attribute.Name = "Attribute";
            this.Attribute.ReadOnly = true;
            this.Attribute.Width = 200;
            // 
            // Value
            // 
            this.Value.DataPropertyName = "Value";
            this.Value.HeaderText = "Value";
            this.Value.Name = "Value";
            this.Value.ReadOnly = true;
            this.Value.Width = 200;
            // 
            // restoreRecordsButton
            // 
            this.restoreRecordsButton.Location = new System.Drawing.Point(226, 80);
            this.restoreRecordsButton.Name = "restoreRecordsButton";
            this.restoreRecordsButton.Size = new System.Drawing.Size(204, 23);
            this.restoreRecordsButton.TabIndex = 14;
            this.restoreRecordsButton.Text = "Restore Records";
            this.restoreRecordsButton.UseVisualStyleBackColor = true;
            this.restoreRecordsButton.Click += new System.EventHandler(this.restoreRecordsButton_Click);
            // 
            // MyPluginControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.restoreRecordsButton);
            this.Controls.Add(this.detailsDataGrid);
            this.Controls.Add(this.deletedRecordGrid);
            this.Controls.Add(this.fetchRecordsBtn);
            this.Controls.Add(this.usersCb);
            this.Controls.Add(this.usernameLabel);
            this.Controls.Add(this.entityLabel);
            this.Controls.Add(this.entitiesCb);
            this.Controls.Add(this.toolStripMenu);
            this.Name = "MyPluginControl";
            this.Size = new System.Drawing.Size(1162, 496);
            this.Load += new System.EventHandler(this.MyPluginControl_Load);
            this.toolStripMenu.ResumeLayout(false);
            this.toolStripMenu.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.deletedRecordGrid)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.detailsDataGrid)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.ToolStrip toolStripMenu;
        private System.Windows.Forms.ToolStripButton tsbClose;
        private System.Windows.Forms.ComboBox entitiesCb;
        private System.Windows.Forms.Label entityLabel;
        private System.Windows.Forms.Label usernameLabel;
        private System.Windows.Forms.ComboBox usersCb;
        private System.Windows.Forms.Button fetchRecordsBtn;
        private System.Windows.Forms.DataGridView deletedRecordGrid;
        private System.Windows.Forms.DataGridViewTextBoxColumn Id;
        private System.Windows.Forms.DataGridViewTextBoxColumn ObjectId;
        private System.Windows.Forms.DataGridViewTextBoxColumn Entity;
        private System.Windows.Forms.DataGridViewTextBoxColumn UserId;
        private System.Windows.Forms.DataGridViewTextBoxColumn CreatedDate;
        private System.Windows.Forms.DataGridView detailsDataGrid;
        private System.Windows.Forms.DataGridViewTextBoxColumn Attribute;
        private System.Windows.Forms.DataGridViewTextBoxColumn Value;
        private System.Windows.Forms.Button restoreRecordsButton;
    }
}
