namespace Xrm.RecordsRestorator.Plugin
{
    partial class MyPluginControl
    {
        /// <summary> 
        /// Variable nécessaire au concepteur.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Nettoyage des ressources utilisées.
        /// </summary>
        /// <param name="disposing">true si les ressources managées doivent être supprimées ; sinon, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by component designer
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MyPluginControl));
            this.toolStripMenu = new System.Windows.Forms.ToolStrip();
            this.tsbClose = new System.Windows.Forms.ToolStripButton();
            this.entitiesCb = new System.Windows.Forms.ComboBox();
            this.entityLabel = new System.Windows.Forms.Label();
            this.usernameLabel = new System.Windows.Forms.Label();
            this.usersCb = new System.Windows.Forms.ComboBox();
            this.fetchRecordsBtn = new System.Windows.Forms.Button();
            this.deletedRecordGrid = new System.Windows.Forms.DataGridView();
            this.Id = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.ObjectId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Entity = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.UserId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.CreatedDate = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.detailsDataGrid = new System.Windows.Forms.DataGridView();
            this.Attribute = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Value = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.restoreRecordsButton = new System.Windows.Forms.Button();
            this.objectTextBox = new System.Windows.Forms.TextBox();
            this.objectLabel = new System.Windows.Forms.Label();
            this.fromDateTimePicker = new System.Windows.Forms.DateTimePicker();
            this.toDateTimePicker = new System.Windows.Forms.DateTimePicker();
            this.fromDateLabel = new System.Windows.Forms.Label();
            this.toDateLabel = new System.Windows.Forms.Label();
            this.toolStripMenu.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.deletedRecordGrid)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.detailsDataGrid)).BeginInit();
            this.SuspendLayout();
            // 
            // toolStripMenu
            // 
            this.toolStripMenu.ImageScalingSize = new System.Drawing.Size(24, 24);
            this.toolStripMenu.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.tsbClose});
            this.toolStripMenu.Location = new System.Drawing.Point(0, 0);
            this.toolStripMenu.Name = "toolStripMenu";
            this.toolStripMenu.Size = new System.Drawing.Size(1549, 27);
            this.toolStripMenu.TabIndex = 4;
            this.toolStripMenu.Text = "toolStrip1";
            // 
            // tsbClose
            // 
            this.tsbClose.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.tsbClose.Name = "tsbClose";
            this.tsbClose.Size = new System.Drawing.Size(107, 24);
            this.tsbClose.Text = "Close this tool";
            this.tsbClose.Click += new System.EventHandler(this.tsbClose_Click);
            // 
            // entitiesCb
            // 
            this.entitiesCb.FormattingEnabled = true;
            this.entitiesCb.Location = new System.Drawing.Point(96, 32);
            this.entitiesCb.Margin = new System.Windows.Forms.Padding(4);
            this.entitiesCb.Name = "entitiesCb";
            this.entitiesCb.Size = new System.Drawing.Size(196, 24);
            this.entitiesCb.TabIndex = 6;
            this.entitiesCb.SelectedIndexChanged += new System.EventHandler(this.entitiesCb_SelectedIndexChanged);
            // 
            // entityLabel
            // 
            this.entityLabel.AutoSize = true;
            this.entityLabel.Location = new System.Drawing.Point(17, 36);
            this.entityLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.entityLabel.Name = "entityLabel";
            this.entityLabel.Size = new System.Drawing.Size(39, 16);
            this.entityLabel.TabIndex = 7;
            this.entityLabel.Text = "Entity";
            // 
            // usernameLabel
            // 
            this.usernameLabel.AutoSize = true;
            this.usernameLabel.Location = new System.Drawing.Point(15, 69);
            this.usernameLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.usernameLabel.Name = "usernameLabel";
            this.usernameLabel.Size = new System.Drawing.Size(70, 16);
            this.usernameLabel.TabIndex = 8;
            this.usernameLabel.Text = "Username";
            // 
            // usersCb
            // 
            this.usersCb.FormattingEnabled = true;
            this.usersCb.Location = new System.Drawing.Point(96, 65);
            this.usersCb.Margin = new System.Windows.Forms.Padding(4);
            this.usersCb.Name = "usersCb";
            this.usersCb.Size = new System.Drawing.Size(196, 24);
            this.usersCb.TabIndex = 9;
            this.usersCb.SelectedIndexChanged += new System.EventHandler(this.usersCb_SelectedIndexChanged);
            // 
            // fetchRecordsBtn
            // 
            this.fetchRecordsBtn.Location = new System.Drawing.Point(21, 98);
            this.fetchRecordsBtn.Margin = new System.Windows.Forms.Padding(4);
            this.fetchRecordsBtn.Name = "fetchRecordsBtn";
            this.fetchRecordsBtn.Size = new System.Drawing.Size(272, 28);
            this.fetchRecordsBtn.TabIndex = 10;
            this.fetchRecordsBtn.Text = "Fetch Records";
            this.fetchRecordsBtn.UseVisualStyleBackColor = true;
            this.fetchRecordsBtn.Click += new System.EventHandler(this.fetchRecordsBtn_Click);
            // 
            // deletedRecordGrid
            // 
            this.deletedRecordGrid.AllowUserToAddRows = false;
            this.deletedRecordGrid.AllowUserToDeleteRows = false;
            this.deletedRecordGrid.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.deletedRecordGrid.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.deletedRecordGrid.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Id,
            this.ObjectId,
            this.Entity,
            this.UserId,
            this.CreatedDate});
            this.deletedRecordGrid.Location = new System.Drawing.Point(19, 162);
            this.deletedRecordGrid.Margin = new System.Windows.Forms.Padding(4);
            this.deletedRecordGrid.Name = "deletedRecordGrid";
            this.deletedRecordGrid.ReadOnly = true;
            this.deletedRecordGrid.RowHeadersWidth = 51;
            this.deletedRecordGrid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.deletedRecordGrid.ShowCellErrors = false;
            this.deletedRecordGrid.ShowEditingIcon = false;
            this.deletedRecordGrid.ShowRowErrors = false;
            this.deletedRecordGrid.Size = new System.Drawing.Size(827, 416);
            this.deletedRecordGrid.TabIndex = 12;
            this.deletedRecordGrid.Click += new System.EventHandler(this.deletedRecordGrid_Click);
            // 
            // Id
            // 
            this.Id.DataPropertyName = "Id";
            this.Id.HeaderText = "ID";
            this.Id.MinimumWidth = 6;
            this.Id.Name = "Id";
            this.Id.ReadOnly = true;
            this.Id.Visible = false;
            this.Id.Width = 125;
            // 
            // ObjectId
            // 
            this.ObjectId.DataPropertyName = "ObjectId";
            this.ObjectId.HeaderText = "Object";
            this.ObjectId.MinimumWidth = 6;
            this.ObjectId.Name = "ObjectId";
            this.ObjectId.ReadOnly = true;
            this.ObjectId.Width = 220;
            // 
            // Entity
            // 
            this.Entity.DataPropertyName = "Entity";
            this.Entity.HeaderText = "Entity";
            this.Entity.MinimumWidth = 6;
            this.Entity.Name = "Entity";
            this.Entity.ReadOnly = true;
            this.Entity.Width = 125;
            // 
            // UserId
            // 
            this.UserId.DataPropertyName = "UserId";
            this.UserId.HeaderText = "User";
            this.UserId.MinimumWidth = 6;
            this.UserId.Name = "UserId";
            this.UserId.ReadOnly = true;
            this.UserId.Width = 150;
            // 
            // CreatedDate
            // 
            this.CreatedDate.DataPropertyName = "CreatedDate";
            this.CreatedDate.HeaderText = "Date";
            this.CreatedDate.MinimumWidth = 6;
            this.CreatedDate.Name = "CreatedDate";
            this.CreatedDate.ReadOnly = true;
            this.CreatedDate.Width = 125;
            // 
            // detailsDataGrid
            // 
            this.detailsDataGrid.AllowUserToAddRows = false;
            this.detailsDataGrid.AllowUserToDeleteRows = false;
            this.detailsDataGrid.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.detailsDataGrid.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.detailsDataGrid.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Attribute,
            this.Value});
            this.detailsDataGrid.Location = new System.Drawing.Point(880, 162);
            this.detailsDataGrid.Margin = new System.Windows.Forms.Padding(4);
            this.detailsDataGrid.MultiSelect = false;
            this.detailsDataGrid.Name = "detailsDataGrid";
            this.detailsDataGrid.ReadOnly = true;
            this.detailsDataGrid.RowHeadersWidth = 51;
            this.detailsDataGrid.ShowEditingIcon = false;
            this.detailsDataGrid.Size = new System.Drawing.Size(627, 416);
            this.detailsDataGrid.TabIndex = 13;
            // 
            // Attribute
            // 
            this.Attribute.DataPropertyName = "Key";
            this.Attribute.HeaderText = "Attribute";
            this.Attribute.MinimumWidth = 6;
            this.Attribute.Name = "Attribute";
            this.Attribute.ReadOnly = true;
            this.Attribute.Width = 200;
            // 
            // Value
            // 
            this.Value.DataPropertyName = "Value";
            this.Value.HeaderText = "Value";
            this.Value.MinimumWidth = 6;
            this.Value.Name = "Value";
            this.Value.ReadOnly = true;
            this.Value.Width = 200;
            // 
            // restoreRecordsButton
            // 
            this.restoreRecordsButton.Location = new System.Drawing.Point(301, 98);
            this.restoreRecordsButton.Margin = new System.Windows.Forms.Padding(4);
            this.restoreRecordsButton.Name = "restoreRecordsButton";
            this.restoreRecordsButton.Size = new System.Drawing.Size(272, 28);
            this.restoreRecordsButton.TabIndex = 14;
            this.restoreRecordsButton.Text = "Restore Records";
            this.restoreRecordsButton.UseVisualStyleBackColor = true;
            this.restoreRecordsButton.Click += new System.EventHandler(this.restoreRecordsButton_Click);
            // 
            // objectTextBox
            // 
            this.objectTextBox.Location = new System.Drawing.Point(356, 32);
            this.objectTextBox.Margin = new System.Windows.Forms.Padding(4);
            this.objectTextBox.Name = "objectTextBox";
            this.objectTextBox.Size = new System.Drawing.Size(216, 22);
            this.objectTextBox.TabIndex = 15;
            // 
            // objectLabel
            // 
            this.objectLabel.AutoSize = true;
            this.objectLabel.Location = new System.Drawing.Point(297, 36);
            this.objectLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.objectLabel.Name = "objectLabel";
            this.objectLabel.Size = new System.Drawing.Size(46, 16);
            this.objectLabel.TabIndex = 16;
            this.objectLabel.Text = "Object";
            // 
            // fromDateTimePicker
            // 
            this.fromDateTimePicker.Checked = false;
            this.fromDateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.fromDateTimePicker.Location = new System.Drawing.Point(631, 32);
            this.fromDateTimePicker.Margin = new System.Windows.Forms.Padding(4);
            this.fromDateTimePicker.Name = "fromDateTimePicker";
            this.fromDateTimePicker.ShowCheckBox = true;
            this.fromDateTimePicker.Size = new System.Drawing.Size(156, 22);
            this.fromDateTimePicker.TabIndex = 17;
            this.fromDateTimePicker.Value = new System.DateTime(2020, 1, 1, 0, 0, 0, 0);
            this.fromDateTimePicker.ValueChanged += new System.EventHandler(this.fromDateTimePicker_ValueChanged);
            // 
            // toDateTimePicker
            // 
            this.toDateTimePicker.Checked = false;
            this.toDateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.toDateTimePicker.Location = new System.Drawing.Point(631, 66);
            this.toDateTimePicker.Margin = new System.Windows.Forms.Padding(4);
            this.toDateTimePicker.Name = "toDateTimePicker";
            this.toDateTimePicker.ShowCheckBox = true;
            this.toDateTimePicker.Size = new System.Drawing.Size(156, 22);
            this.toDateTimePicker.TabIndex = 18;
            this.toDateTimePicker.Value = new System.DateTime(2020, 1, 1, 0, 0, 0, 0);
            this.toDateTimePicker.ValueChanged += new System.EventHandler(this.toDateTimePicker_ValueChanged);
            // 
            // fromDateLabel
            // 
            this.fromDateLabel.AutoSize = true;
            this.fromDateLabel.Location = new System.Drawing.Point(583, 41);
            this.fromDateLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.fromDateLabel.Name = "fromDateLabel";
            this.fromDateLabel.Size = new System.Drawing.Size(38, 16);
            this.fromDateLabel.TabIndex = 19;
            this.fromDateLabel.Text = "From";
            // 
            // toDateLabel
            // 
            this.toDateLabel.AutoSize = true;
            this.toDateLabel.Location = new System.Drawing.Point(583, 69);
            this.toDateLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.toDateLabel.Name = "toDateLabel";
            this.toDateLabel.Size = new System.Drawing.Size(24, 16);
            this.toDateLabel.TabIndex = 20;
            this.toDateLabel.Text = "To";
            // 
            // MyPluginControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.toDateLabel);
            this.Controls.Add(this.fromDateLabel);
            this.Controls.Add(this.toDateTimePicker);
            this.Controls.Add(this.fromDateTimePicker);
            this.Controls.Add(this.objectLabel);
            this.Controls.Add(this.objectTextBox);
            this.Controls.Add(this.restoreRecordsButton);
            this.Controls.Add(this.detailsDataGrid);
            this.Controls.Add(this.deletedRecordGrid);
            this.Controls.Add(this.fetchRecordsBtn);
            this.Controls.Add(this.usersCb);
            this.Controls.Add(this.usernameLabel);
            this.Controls.Add(this.entityLabel);
            this.Controls.Add(this.entitiesCb);
            this.Controls.Add(this.toolStripMenu);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "MyPluginControl";
            this.PluginIcon = ((System.Drawing.Icon)(resources.GetObject("$this.PluginIcon")));
            this.Size = new System.Drawing.Size(1549, 610);
            this.TabIcon = global::Xrm.RecordsRestorator.Plugin.Properties.Resources.plugin_icon32px;
            this.Load += new System.EventHandler(this.MyPluginControl_Load);
            this.toolStripMenu.ResumeLayout(false);
            this.toolStripMenu.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.deletedRecordGrid)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.detailsDataGrid)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.ToolStrip toolStripMenu;
        private System.Windows.Forms.ToolStripButton tsbClose;
        private System.Windows.Forms.ComboBox entitiesCb;
        private System.Windows.Forms.Label entityLabel;
        private System.Windows.Forms.Label usernameLabel;
        private System.Windows.Forms.ComboBox usersCb;
        private System.Windows.Forms.Button fetchRecordsBtn;
        private System.Windows.Forms.DataGridView deletedRecordGrid;
        private System.Windows.Forms.DataGridViewTextBoxColumn Id;
        private System.Windows.Forms.DataGridViewTextBoxColumn ObjectId;
        private System.Windows.Forms.DataGridViewTextBoxColumn Entity;
        private System.Windows.Forms.DataGridViewTextBoxColumn UserId;
        private System.Windows.Forms.DataGridViewTextBoxColumn CreatedDate;
        private System.Windows.Forms.DataGridView detailsDataGrid;
        private System.Windows.Forms.DataGridViewTextBoxColumn Attribute;
        private System.Windows.Forms.DataGridViewTextBoxColumn Value;
        private System.Windows.Forms.Button restoreRecordsButton;
        private System.Windows.Forms.TextBox objectTextBox;
        private System.Windows.Forms.Label objectLabel;
        private System.Windows.Forms.DateTimePicker fromDateTimePicker;
        private System.Windows.Forms.DateTimePicker toDateTimePicker;
        private System.Windows.Forms.Label fromDateLabel;
        private System.Windows.Forms.Label toDateLabel;
    }
}
